apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-my-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: pharmacyvolumemanual
  awsElasticBlockStore:
    volumeID: vol-0c563942b72557111
    fsType: ext4
